#!/bin/bash
#
    
RED_TEXT="\033[31m"
BLUE_TEXT="\033[34m"
GREEN_TEXT="\033[32m"
ENTER_LINE="\033[32m"

web="https://sl0ppyr00t.tk"
author="p.hoogeveen"
name="sl0ppy-lfi"
build="20220405"
version="v0.1"
aka="~x0xr00t~"
user="x0"
show_menu(){
    NORMAL="\033[m" 
    MENU="\033[32m" #green
    NUMBER="\033[34m" #blue
    FGRED="\033[41m"
    RED_TEXT="\033[31m"
    BLUE_TEXT="\033[34m"
    GREEN_TEXT="\033[32m"
    YELLOW_TEXT="\033[33m"
    MAGNETA_TEXT="\033[35m" 
    CYAN_TEXT="\033[36m"  
    BLINK="\e[5m"
    ENTER_LINE="\033[32m"
    echo -e "${ENTER_LINE}${GREEN_TEXT} ${NORMAL}"
    echo -e "${RED_TEXT}     _  ___                          _  __ _ "
    echo -e "${RED_TEXT} ___| |/ _ \ _ __  _ __  _   _      | |/ _(_)"
    echo -e "${RED_TEXT}/ __| | | | | '_ \| '_ \| | | |_____| | |_| |"
    echo -e "${RED_TEXT}\__ \ | |_| | |_) | |_) | |_| |_____| |  _| |"
    echo -e "${RED_TEXT}|___/_|\___/| .__/| .__/ \__, |     |_|_| |_|"
    echo -e "${RED_TEXT}            |_|   |_|    |___/               ${NORMAL}"
    echo -e "${ENTER_LINE}      This is ${RED_TEXT}a${GREEN_TEXT} Official ${BLUE_TEXT} $crew Build ${NORMAL}"
    echo -e "${MENU}       **************************************${NORMAL}"
    echo -e "${MENU}       *${NUMBER} 1)${YELLOW_TEXT} Windows-LFI Checks               *${NORMAL}"
    echo -e "${MENU}       *${NUMBER} 2)${YELLOW_TEXT} Linux-LFI Checks                *${NORMAL}"
    echo -e "${MENU}       *${NUMBER} 3)${YELLOW_TEXT} All-Files-LFI Checks             *${NORMAL}"
    echo -e "${MENU}       **************************************${NORMAL}"
    echo -e "${ENTER_LINE} ${RED_TEXT} {!}${BLUE_TEXT} Follow all the instructions${GREEN_TEXT} and you will be good${RED_TEXT}{!}${NOMRAL}"    
    echo -e "${ENTER_LINE} ${RED_TEXT} {v}${BLUE_TEXT} Coded By:${RED_TEXT} $author ||${BLUE_TEXT} $aka ||${RED_TEXT} |${BLUE_TEXT} $website "
    echo -e "${ENTER_LINE} ${RED_TEXT} {v}${BLUE_TEXT} Please enter a menu option and enter or ${RED_TEXT}enter to exit. ${NORMAL}"
    read opt 
}

function option_picked() {
    COLOR='\033[01;31m' # bold red
    RESET='\033[00;00m' # normal white
    MESSAGE=${@:-"${RESET}Error: No message passed"}
    echo -e "${COLOR}${MESSAGE}${RESET}"
}

show_menu
  while [ opt != '' ]
  do
    if [[ $opt = "" ]]; then
      exit;
    else
      case $opt in
      1) clear;
      option_picked "Windows LFI Scan Picked";
      echo -e "${RED_TEXT}     _  ___                          _  __ _ "
      echo -e "${RED_TEXT} ___| |/ _ \ _ __  _ __  _   _      | |/ _(_)"
      echo -e "${RED_TEXT}/ __| | | | | '_ \| '_ \| | | |_____| | |_| |"
      echo -e "${RED_TEXT}\__ \ | |_| | |_) | |_) | |_| |_____| |  _| |"
      echo -e "${RED_TEXT}|___/_|\___/| .__/| .__/ \__, |     |_|_| |_|"
      echo -e "${RED_TEXT}            |_|   |_|    |___/               ${NORMAL}" 
      echo ""
      echo ""
      read -p "Please Enter The LFI Url: " url
      echo ""
      echo ""
      exec /home/$user/sl0ppy-lfi/sl0ppy-windows-lfi $url      
      show_menu;
      ;;

      2) clear;
      option_picked "Linux LFI Scan Picked";
      echo -e "${RED_TEXT}     _  ___                          _  __ _ "
      echo -e "${RED_TEXT} ___| |/ _ \ _ __  _ __  _   _      | |/ _(_)"
      echo -e "${RED_TEXT}/ __| | | | | '_ \| '_ \| | | |_____| | |_| |"
      echo -e "${RED_TEXT}\__ \ | |_| | |_) | |_) | |_| |_____| |  _| |"
      echo -e "${RED_TEXT}|___/_|\___/| .__/| .__/ \__, |     |_|_| |_|"
      echo -e "${RED_TEXT}            |_|   |_|    |___/               ${NORMAL}"  
      echo ""
      echo ""
      read -p "Please Enter The LFI Url: " url
      echo ""
      echo ""
      exec /home/$user/sl0ppy-lfi/sl0ppy-linux-lfi $url      
      show_menu;
      ;;

      3) clear;
      option_picked "Lin-Win-LFI Scan Picked";
      echo -e "${RED_TEXT}     _  ___                          _  __ _ "
      echo -e "${RED_TEXT} ___| |/ _ \ _ __  _ __  _   _      | |/ _(_)"
      echo -e "${RED_TEXT}/ __| | | | | '_ \| '_ \| | | |_____| | |_| |"
      echo -e "${RED_TEXT}\__ \ | |_| | |_) | |_) | |_| |_____| |  _| |"
      echo -e "${RED_TEXT}|___/_|\___/| .__/| .__/ \__, |     |_|_| |_|"
      echo -e "${RED_TEXT}            |_|   |_|    |___/               ${NORMAL}"  
      echo ""
      echo ""
      read -p "Please Enter The LFI Url: " url
      echo ""
      echo ""
      exec /home/$user/sl0ppy-lfi/sl0ppy-lin-win-lfi $url 
      show_menu;
      ;;

      #4) clear;
      #option_picked "Option 4 Picked";
      #show_menu;
      #;;
      #5) clear;
      #option_picked "Option 5 Picked";
      #ub_menu1;
      #;;

      x)exit;
      ;;

      \n)exit;
      ;;

      *)clear;
      option_picked "Pick an option from the menu";
      show_menu;
      ;;
      esac
    fi
  done
}

function option_picked() {
    COLOR='\033[01;31m' # bold red
    RESET='\033[00;00m' # normal white
    MESSAGE=${@:-"${RESET}Error: No message passed"}
    echo -e "${COLOR}${MESSAGE}${RESET}"
}

sub_menu1(){
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${MENU}**${NUMBER} 1)${MENU} Sub Option1 ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 2)${MENU} Sub Option2 ${NORMAL}"
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${ENTER_LINE}Please enter a menu option and enter or ${RED_TEXT}enter to exit. ${NORMAL}"
    read sub1
  while [ sub1 != '' ]
  do
    if [[ $sub1 = "" ]]; then
      exit;
    else
      case $sub1 in
      1) clear;
      option_picked "Sub menu option 1";
      echo "test"
      sub_menu_admin;
      ;;

      2) clear;
      option_picked "Sub menu option 2";
      echo "test"
      sub_menu_admin;
      ;;

      x)exit;
      ;;

      \n)exit;
      ;;

      *)clear;
      option_picked "Pick an option from the menu";
      sub_menu1;
      ;;
      esac
    fi
  done
}

clear
show_menu;      


echo -e "${RED_TEXT}     _  ___                          _  __ _ "
echo -e "${RED_TEXT} ___| |/ _ \ _ __  _ __  _   _      | |/ _(_)"
echo -e "${RED_TEXT}/ __| | | | | '_ \| '_ \| | | |_____| | |_| |"
echo -e "${RED_TEXT}\__ \ | |_| | |_) | |_) | |_| |_____| |  _| |"
echo -e "${RED_TEXT}|___/_|\___/| .__/| .__/ \__, |     |_|_| |_|"
echo -e "${RED_TEXT}            |_|   |_|    |___/               ${NORMAL}"                                                                                                                                                                                         
echo -e "${ENTER_LINE} ${GREEN_TEXT}Thnx for using our installer || ${BLUE_TEXT}Coded By NomenNescio || ~%|\| |\|%~ ${RED_TEXT}|| 53|\|5|3 ${NOMRAL}"
